#include "UnrealGrpcEditorDelegates.h"

FUnrealGrpcEditorDelegates::FOnSettingsApplied FUnrealGrpcEditorDelegates::OnSettingsApplied;

FUnrealGrpcEditorDelegates::FOnNewProtoApplied FUnrealGrpcEditorDelegates::OnNewProtoApplied;
